import argparse
import json
import re
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = PROJECT_ROOT / "tests" / "outputs"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(PROJECT_ROOT))

import app.graph as graph_module  # noqa: E402
import app.memory.context_strategy as context_strategy_module  # noqa: E402


DEFAULT_QUESTION = "2026-05-21新增用户量是多少"
DEFAULT_SESSION_ID = "mock-bedrock-full-loop-validation"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the full local analytics loop with Bedrock mocked.",
    )
    parser.add_argument(
        "--question",
        default=DEFAULT_QUESTION,
        help="Question to run through the graph.",
    )
    parser.add_argument(
        "--session-id",
        default=DEFAULT_SESSION_ID,
        help="Session id used by memory storage.",
    )
    parser.add_argument(
        "--request-id",
        default=None,
        help="Optional request id. A timestamped id is generated by default.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional output JSON path.",
    )
    parser.add_argument(
        "--allow-tool-failure",
        action="store_true",
        help="Write the report but exit 0 even when SQL tool calls fail.",
    )
    return parser.parse_args()


def mock_bedrock_json(prompt: str) -> Dict[str, Any]:
    question = _extract_question_from_prompt(prompt)
    params = _parse_time_params(question)

    if _contains_dimension(question):
        params["dimension"] = "level"

    limit = _extract_limit(question)
    if limit:
        params["limit"] = limit

    return {
        "metric": "user_count",
        "params": params,
    }


def mock_bedrock_text(prompt: str) -> str:
    return (
        "Mock Bedrock summary: 真实 Bedrock 当前不可用，本次仅用于验证 "
        "Planner 之后的分析闭环。"
    )


def mock_context_strategy_json(prompt: str) -> Dict[str, Any]:
    return {
        "use_context": False,
        "reset_context": False,
        "reason": "mock_bedrock_context_disabled",
    }


def _extract_question_from_prompt(prompt: str) -> str:
    match = re.search(r"用户问题：\s*(.*?)\s*输出格式：", prompt, re.S)
    if match:
        return match.group(1).strip()

    return prompt


def _parse_time_params(question: str) -> Dict[str, Any]:
    date_matches = re.findall(r"\d{4}-\d{2}-\d{2}", question)

    if len(date_matches) >= 2:
        start_dt = datetime.strptime(date_matches[0], "%Y-%m-%d")
        end_dt = datetime.strptime(date_matches[1], "%Y-%m-%d") + timedelta(days=1)
        return {
            "start_time": start_dt.strftime("%Y-%m-%d"),
            "end_time": end_dt.strftime("%Y-%m-%d"),
            "grain": "day",
        }

    if len(date_matches) == 1:
        start_dt = datetime.strptime(date_matches[0], "%Y-%m-%d")
        end_dt = start_dt + timedelta(days=1)
        return {
            "start_time": start_dt.strftime("%Y-%m-%d"),
            "end_time": end_dt.strftime("%Y-%m-%d"),
            "grain": "day",
        }

    raise ValueError(
        "Mock Bedrock parser requires at least one YYYY-MM-DD date in the question."
    )


def _contains_dimension(question: str) -> bool:
    dimension_keywords = [
        "level",
        "等级",
        "用户等级",
        "各",
        "按",
        "分布",
    ]
    return any(keyword in question for keyword in dimension_keywords)


def _extract_limit(question: str) -> int | None:
    match = re.search(r"前\s*(\d+)", question)
    if match:
        return int(match.group(1))

    match = re.search(r"top\s*(\d+)", question.lower())
    if match:
        return int(match.group(1))

    return None


def summarize_result(
    question: str,
    request_id: str,
    result: Dict[str, Any],
) -> Dict[str, Any]:
    trace = result.get("trace", {})
    aggregation_plan = result.get("aggregation_plan") or {}
    steps = [
        step.get("step")
        for step in trace.get("steps", [])
    ]

    return {
        "validation_mode": "mock_bedrock_real_graph_and_sql_tool",
        "question": question,
        "request_id": request_id,
        "session_id": result.get("session_id"),
        "answer": result.get("answer"),
        "trace_file": result.get("trace_file"),
        "steps": steps,
        "aggregation_type": aggregation_plan.get("aggregation_type"),
        "tasks": result.get("tasks"),
        "query_plans": result.get("query_plans"),
        "tool_results": result.get("tool_results"),
        "aggregation_result": result.get("aggregation_result"),
        "structured_insight": result.get("structured_insight"),
        "follow_up_suggestions": result.get("follow_up_suggestions"),
    }


def validate_summary(summary: Dict[str, Any]) -> list[str]:
    errors = []

    expected_steps = [
        "plan_tasks",
        "compile_queries",
        "execute_queries",
        "aggregation_analysis",
        "structured_insight",
        "follow_up_suggestions",
        "summarize",
    ]

    steps = summary.get("steps", [])
    missing_steps = [
        step for step in expected_steps
        if step not in steps
    ]

    if missing_steps:
        errors.append(f"Missing graph steps: {missing_steps}")

    query_plans = summary.get("query_plans") or []
    if not query_plans:
        errors.append("No query plans generated.")

    tool_results = summary.get("tool_results") or []
    if not tool_results:
        errors.append("No SQL tool results returned.")

    failed_tool_results = [
        result for result in tool_results
        if not result.get("success")
    ]
    if failed_tool_results:
        errors.append(f"SQL tool failed for {len(failed_tool_results)} task(s).")

    structured_insight = summary.get("structured_insight") or {}
    if not structured_insight.get("main_conclusion"):
        errors.append("Structured insight main_conclusion is empty.")

    if not isinstance(summary.get("follow_up_suggestions"), list):
        errors.append("follow_up_suggestions is not a list.")

    return errors


def write_report(summary: Dict[str, Any], output_path: Path) -> None:
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)


def main() -> None:
    args = parse_args()

    request_id = (
        args.request_id
        or f"mock-bedrock-full-loop-{int(time.time())}"
    )

    output_path = (
        Path(args.output)
        if args.output
        else OUTPUT_DIR / "latest_mock_bedrock_full_loop_report.json"
    )

    graph_module.invoke_bedrock_json = mock_bedrock_json
    graph_module.invoke_bedrock_text = mock_bedrock_text
    context_strategy_module.invoke_bedrock_json = mock_context_strategy_json

    result = graph_module.build_graph().invoke({
        "question": args.question,
        "session_id": args.session_id,
        "request_id": request_id,
    })

    summary = summarize_result(
        question=args.question,
        request_id=request_id,
        result=result,
    )
    validation_errors = validate_summary(summary)
    summary["success"] = not validation_errors
    summary["validation_errors"] = validation_errors

    write_report(summary, output_path)

    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"\nReport written to: {output_path}")

    if validation_errors and not args.allow_tool_failure:
        sys.exit(1)


if __name__ == "__main__":
    main()
